import {
  CreditCard,
  Zap,
  ShieldCheck,
  Smartphone,
  Percent,
  TrendingDown,
  RefreshCw,
  FileText,
  Leaf,
  Clock,
  Home,
  TrendingUp,
  Search,
  Target,
  Share2,
  BarChart3,
  Banknote,
  Megaphone,
  Check,
  HelpCircle,
  Globe,
  Monitor,
  Wallet,
  Headphones,
  Lightbulb,
  Thermometer,
  Wind,
  Droplet,
  HeartHandshake,
  DollarSign,
  Users,
  MessageCircle,
  ClipboardList,
  Settings,
  ShoppingCart,
  Layout,
  Flame,
  Bot,
  Cpu,
  Sparkles,
  Workflow,
  Link2,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

// A curated subset, not the full lucide-react barrel — importing `* as icons`
// would defeat tree-shaking and bundle every icon in the library. Add new
// entries here as admins introduce new icon names through the Services editor.
const ICONS: Record<string, LucideIcon> = {
  CreditCard,
  Zap,
  ShieldCheck,
  Smartphone,
  Percent,
  TrendingDown,
  RefreshCw,
  FileText,
  Leaf,
  Clock,
  Home,
  TrendingUp,
  Search,
  Target,
  Share2,
  BarChart3,
  Banknote,
  Megaphone,
  Check,
  HelpCircle,
  Globe,
  Monitor,
  Wallet,
  Headphones,
  Lightbulb,
  Thermometer,
  Wind,
  Droplet,
  HeartHandshake,
  DollarSign,
  Users,
  MessageCircle,
  ClipboardList,
  Settings,
  ShoppingCart,
  Layout,
  Flame,
  Bot,
  Cpu,
  Sparkles,
  Workflow,
  Link2,
};

export function DynamicIcon({ name, ...props }: { name: string } & LucideProps) {
  const IconComponent = ICONS[name] ?? HelpCircle;
  return <IconComponent {...props} />;
}
